#
# Configuración de la aplicación
# 
spring.application.name=biblioteca-api

# 
# Conexión a MongoDB Atlas
# Reemplaza la URI con tu cadena de conexión real
# obtenida en el Paso 5 de la sección MongoDB Atlas
# 
spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:Biblioteca12345@clusterbiblioteca.jfbdbtw.mongodb.net/biblioteca?retryWrites=true&w=majority&appName=ClusterBiblioteca
# Nombre de la base de datos en MongoDB
spring.data.mongodb.database=biblioteca_db
# 
# Servidor
# 
server.port=8080
