spring.application.name=biblioteca-api

spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:Biblioteca12345@clusterbiblioteca.jfbdbtw.mongodb.net/biblioteca?retryWrites=true&w=majority&appName=ClusterBiblioteca
spring.data.mongodb.database=biblioteca_db

server.port=8080
